apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: romeojuliet.com
      http:
        paths:
          - path: /romeo/rocks
            backend:
              serviceName: romeo-srv
              servicePort: 3001
          - path: /romeo/rocks/throw
            backend:
              serviceName: romeo-srv
              servicePort: 3001
          - path: /juliet/windows
            backend:
              serviceName: juliet-srv
              servicePort: 3002
          - path: /juliet/taptap
            backend:
              serviceName: juliet-srv
              servicePort: 3002
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
